### ISSUE TITLE
TypeError on empty, datetime expected value

### ISSUE THREAD

**Issue by vasil** [Symphony-Splutions-Python-Course/lab1#9]
На прв старт, најверојатно во недостаток на `memcache` запис ми ја даде оваа грешка. 

```
(venv) vasil@vt:~/Projects/lab1$ ./venv/bin/python Maki/http_or_table.py 
Traceback (most recent call last):
  File "Maki/http_or_table.py", line 175, in <module>
    main()
  File "Maki/http_or_table.py", line 36, in main
    update_table()
  File "Maki/http_or_table.py", line 40, in update_table
    content = get_content()
  File "Maki/http_or_table.py", line 90, in get_content
    print("Seconds passed since last update: " + str((datetime.today() - last_date).seconds) + "s")
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```
Пред да читаш атрибут на некој објект провери дали е тоа тоа што мислиш, а јас пробувамк ако оди ова со `github issues` ;)

**Comment by makikaka** [comment]
Интересно. А не ни ја сетирам никаде, освен преку memcache. Сум заборавил на тоа кога ја дотерував. Сега го средив.
